[Music_puls]
enable = true
command = ["点歌", "音乐"]
command-format = "请使用「点歌 歌曲名」格式点歌"
play_command = "播放"
api_url = "https://sdkapi.hhlqilongzhu.cn/api/dgMusic_kugou/"
api_key = "你的key" #请求密钥key请前往龙珠api官群(914956181)自助免费获取
card_type = "摇一摇搜歌"  # 切换为新摇一摇卡片（改为原卡片）
# 新增日志配置
[Music_puls.log]
enabled = true               # 日志总开关（true=启用，false=禁用）
level = "DEBUG"              # 日志级别（可选：DEBUG/INFO/WARNING/ERROR/CRITICAL）

# 新增功能控制配置
[Music_puls.features]
fetch_song_list = false       # 歌曲列表获取开关（true=显示列表，false=直接播放一首歌）
